# Generated by Django 3.2.4 on 2021-06-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
